2021-08-26 12:44:31,251 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-08-26 12:45:01,818 INFO view.course.course Thread-1 : In: getCourses
2021-08-26 12:45:01,825 INFO werkzeug Thread-1 : 127.0.0.1 - - [26/Aug/2021 12:45:01] "GET /course/ HTTP/1.1" 200 -
2021-08-26 14:59:28,855 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-08-26 14:59:32,321 INFO werkzeug Thread-1 : 127.0.0.1 - - [26/Aug/2021 14:59:32] "GET / HTTP/1.1" 200 -
2021-08-26 14:59:42,173 INFO werkzeug Thread-2 : 127.0.0.1 - - [26/Aug/2021 14:59:42] "GET / HTTP/1.1" 200 -
2021-08-26 15:02:19,670 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-08-26 15:03:12,295 INFO werkzeug Thread-1 : 127.0.0.1 - - [26/Aug/2021 15:03:12] "GET / HTTP/1.1" 200 -
2021-08-26 15:03:15,612 INFO view.course.course Thread-2 : In: getCourses
2021-08-26 15:03:15,617 INFO werkzeug Thread-2 : 127.0.0.1 - - [26/Aug/2021 15:03:15] "GET /course/ HTTP/1.1" 200 -
2021-08-26 15:03:50,230 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-08-26 15:03:53,222 INFO view.course.course Thread-1 : In: getCourses
2021-08-26 15:03:53,228 INFO werkzeug Thread-1 : 127.0.0.1 - - [26/Aug/2021 15:03:53] "GET /course/ HTTP/1.1" 200 -
2021-08-26 15:03:53,481 INFO view.course.course Thread-2 : In: getCourses
2021-08-26 15:03:53,483 INFO werkzeug Thread-2 : 127.0.0.1 - - [26/Aug/2021 15:03:53] "GET /course/ HTTP/1.1" 200 -
2021-08-26 15:05:26,963 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-08-26 15:05:29,509 INFO view.course.course Thread-1 : In: getCourses
2021-08-26 15:05:29,513 ERROR app Thread-1 : Exception on /course/ [GET]
Traceback (most recent call last):
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/view/course/course.py", line 17, in getCourses
    connection = mysql.connection.cursor()
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask_mysqldb/__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask_mysqldb/__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1049, "Unknown database 'coachin'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/env/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/gauravkantrod/PycharmProjects/deploymentProject/view/course/course.py", line 25, in getCourses
    except mysql.connector.Error as err:
AttributeError: 'MySQL' object has no attribute 'connector'
2021-08-26 15:05:29,520 INFO werkzeug Thread-1 : 127.0.0.1 - - [26/Aug/2021 15:05:29] "[35m[1mGET /course/ HTTP/1.1[0m" 500 -
